### ISSUE TITLE
Add Run in Postman and Share on Twitter buttons

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/topmate-readme-badge#26]
As shown in the [Figma mocks](https://www.figma.com/file/DGSis1DiZrULEiWydKtpJb/Peerlist), let's add the `Run in Postman` and `Share on Twitter` buttons.

**Comment by zainbinfurqan** [comment]
@vinitshahdeo  Can i work on it?

**Comment by yashvi2001** [comment]
https://github.com/vinitshahdeo/topmate-readme-badge/pull/33  - issue solved #33

**Comment by vinitshahdeo** [comment]
Thanks, @yashvi2001 
Closing this issue.
