### ISSUE TITLE
Fix `Claim your Topmate link`

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/topmate-readme-badge#27]
Clicking on the `Claim your Topmate link` should open [topmate.io](https://topmate.io/) in a new tab.

**Comment by udaykahar** [comment]
Can i work on it?

**Comment by rohitroy-github** [comment]
I checked, it's opening to the exact link you want it to open ? 

![image](https://user-images.githubusercontent.com/68563695/197296757-b8d65c75-95ef-442d-830e-2a7a403ba74f.png)

You are talking about that blue text right ? 
Have you fixed it already, if not you can assign it to me.

**Comment by vinitshahdeo** [comment]
Hey, this was related to the link available in the UI: https://deploy-preview-43--topmate-readme-badge.netlify.app/

This has been fixed now. Thank you.
