### ISSUE TITLE
Add a hyperlink for getting `Peerlist` badge

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/topmate-readme-badge#28]
`Click here to get your peerlist badge` -> should redirect to [this](https://github.com/vinitshahdeo/peerlist-readme-badge)

**Comment by BobinMathew** [comment]
Hi, I would like to work on this task. Can you assign this task to me?

**Comment by BobinMathew** [comment]
where do you want to place this hyperlink.

**Comment by vinitshahdeo** [comment]
Hey, this has been fixed now. Apologies.
