### ISSUE TITLE
Fix CSS in header

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/topmate-readme-badge#29]
<img width="1345" alt="Screenshot 2022-10-22 at 2 19 03 AM" src="https://user-images.githubusercontent.com/20594326/197286252-c382f4c5-f3e6-4758-944c-dd5cf93e60f3.png">

Changes to be made:

1. The size of logo should be consistent with the Figma mocks.
2. Fix the size of `Claim topmate link` button
3. Have consistent spacing b/w the buttons in the header

> [Figma mocks](https://www.figma.com/file/DGSis1DiZrULEiWydKtpJb/Peerlist?node-id=89%3A7)

**Comment by udaykahar** [comment]
Can i work on it?

**Comment by Ishikasaraf20** [comment]
hey @vinitshahdeo  can you assign this issue to me i can work on it

**Comment by vinitshahdeo** [comment]
Hey, the UI has been changed. This issue is no longer valid.
