### ISSUE TITLE
Postman and Twitter icon should be center aligned

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/topmate-readme-badge#45]
![Screenshot 2022-10-29 at 10 31 23 PM](https://user-images.githubusercontent.com/20594326/198843970-317a4641-2868-4f48-ab45-421716a582df.png)

**Comment by siddhesh-desai** [comment]
I'd like to work on it please assign it to me @vinitshahdeo

**Comment by mani-rsg** [comment]
Since its open, I will work on this

**Comment by vinitshahdeo** [comment]
Hey @mani-rsg 

Thanks for your PR. It's merged now. Apologies @siddhesh-desai 🙏
