### ISSUE TITLE
The GitHub buttons on header should be centre-aligned in mobile view

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/topmate-readme-badge#46]
![Screenshot 2022-10-29 at 10 43 35 PM](https://user-images.githubusercontent.com/20594326/198844535-e035f11d-b73a-4759-ae03-5d5a08b57e9c.png)

![Screenshot 2022-10-29 at 10 44 59 PM](https://user-images.githubusercontent.com/20594326/198844570-52245543-3442-4fa3-8657-8a6fd5a39483.png)

**Comment by siddhesh-desai** [comment]
I'd like to work on this. Please assign it to me @vinitshahdeo

**Comment by mani-rsg** [comment]
If its still open I can also work on this

**Comment by vinitshahdeo** [comment]
This is fixed now. Closing this issue.
