### ISSUE TITLE
Create a React App to generate Topmate README Badges

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/topmate-readme-badge#9]
The idea is to create a web app similar to [Badges Generator](https://badgesgenerator.com/) or [Shields.io](https://shields.io/) to generate Topmate README badges. 

### Contributing guide

Please branch off from `feature/web-app` and raise a PR to `feature/web-app`. Currently, this branch contains a client directory that contains a basic React boilerplate which can be developed further as a React app to generate Topmate badges dynamically. 

### API documentation

```markdown
![topmate](https://topmate-readme-badge.herokuapp.com/vinitshahdeo)
```

![topmate](https://topmate-readme-badge.herokuapp.com/vinitshahdeo)

Please refer to the [Postman collection](https://github.com/vinitshahdeo/topmate-readme-badge#api-documentation).

### Local development

```bash
git checkout feature/web-app
cd client/topmate-readme-badge
npm install
npm run start
```

### Related

- Try out: [Peerlist README Badge Generator](https://peerlist-readme-badge.netlify.app/)
- Refer to [this repository](https://github.com/vinitshahdeo/peerlist-readme-badge)

> In case, you have other frameworks in mind, please check out a branch feature/web-app-<your framework> from `develop` and create your app within the client directory.

**Comment by yhoungdev** [comment]
will like to work on this with you

**Comment by vinitshahdeo** [comment]
Hey @Yash-Yadav-git @yhoungdev 

Thanks for your interest. This has been created: https://deploy-preview-43--topmate-readme-badge.netlify.app/

Apologies - I couldn't assign this to you.
